# cargo-deny configuration (CI step "dependency advisories and licenses").
[graph]
all-features = false

[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
confidence-threshold = 0.9
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
    "0BSD",
]

[[licenses.clarify]]
crate = "ring"
expression = "Apache-2.0 AND ISC"
license-files = []
