//! OpenAI Codex driver.
//!
//! Process: the pinned `codex-acp` adapter (`@agentclientprotocol/codex-acp`, a stdio ACP
//! server that starts the Codex *app server* and maps its events to ACP) driving the pinned
//! Codex CLI. Verified against codex-acp 1.13.1 / codex-cli 0.156.1–0.157.1:
//!
//! * `codex-acp --version` prints `@agentclientprotocol/codex-acp <version>`.
//! * Authentication is read from `$CODEX_HOME/auth.json` (ChatGPT login). With
//!   `NO_BROWSER=1` the adapter hides browser login methods; acp-runner never calls
//!   ACP `authenticate`. Without login state `session/new` fails with `-32000
//!   Authentication required` -> `AuthEnrollmentRequired`.
//! * `CODEX_HOME` must exist before Codex starts (it refuses otherwise) and must not live
//!   under `/tmp` (Codex refuses to create helper binaries there).
//! * `INITIAL_AGENT_MODE=agent-full-access` maps to approval `never` + sandbox
//!   `danger-full-access`: the Kubernetes sandbox (pod, optional gVisor) is the isolation
//!   boundary, Codex' own Linux sandbox (Landlock/seccomp/bwrap) generally cannot run inside
//!   an unprivileged container. Configurable via `driverConfig.mode`.
//! * `codex login status` exits 0 with `Logged in using ChatGPT` (stderr) for ChatGPT auth,
//!   `Logged in using an API key - ...` for API keys (rejected by policy) and exits 1 with
//!   `Not logged in` otherwise.

use crate::acp_driver::{AcpLaunch, AcpProcess};
use crate::{
    AgentDriver, AgentProcess, AuthState, DriverContext, DriverError, ProbeReport, cfg_env, cfg_str, cfg_str_list, env,
};
use async_trait::async_trait;
use std::path::{Path, PathBuf};
use std::time::Duration;

pub struct CodexDriver;

pub const DEFAULT_MODE: &str = "agent-full-access";
const ALLOWED_MODES: &[&str] = &["read-only", "agent", "agent-full-access"];

impl CodexDriver {
    pub fn codex_home(ctx: &DriverContext) -> PathBuf {
        ctx.home.join(".codex")
    }

    fn adapter(ctx: &DriverContext) -> String {
        cfg_str(&ctx.config, "adapterCommand").unwrap_or_else(|| "codex-acp".into())
    }

    fn codex_cli(ctx: &DriverContext) -> String {
        cfg_str(&ctx.config, "codexCommand").unwrap_or_else(|| "codex".into())
    }

    fn driver_env(ctx: &DriverContext) -> Result<Vec<(String, String)>, DriverError> {
        let mode = cfg_str(&ctx.config, "mode").unwrap_or_else(|| DEFAULT_MODE.into());
        if !ALLOWED_MODES.contains(&mode.as_str()) {
            return Err(DriverError::Config(format!("codex mode {mode:?} not in {ALLOWED_MODES:?}")));
        }
        let home = Self::codex_home(ctx);
        let mut e = vec![
            ("CODEX_HOME".to_string(), home.to_string_lossy().to_string()),
            ("NO_BROWSER".to_string(), "1".to_string()),
            ("INITIAL_AGENT_MODE".to_string(), mode),
            ("APP_SERVER_LOGS".to_string(), home.join("log").to_string_lossy().to_string()),
        ];
        if let Some(p) = resolve_in_path(&Self::codex_cli(ctx), ctx.path_env.as_deref()) {
            e.push(("CODEX_PATH".into(), p.to_string_lossy().to_string()));
        }
        let mut session_cfg = serde_json::Map::new();
        if let Some(m) = cfg_str(&ctx.config, "model") {
            session_cfg.insert("model".into(), m.into());
        }
        if let Some(r) = cfg_str(&ctx.config, "reasoningEffort") {
            session_cfg.insert("model_reasoning_effort".into(), r.into());
        }
        if let Some(extra) = ctx.config.get("codexConfig").and_then(|v| v.as_object()) {
            for (k, v) in extra {
                session_cfg.insert(k.clone(), v.clone());
            }
        }
        if !session_cfg.is_empty() {
            e.push(("CODEX_CONFIG".into(), serde_json::Value::Object(session_cfg).to_string()));
        }
        e.extend(cfg_env(&ctx.config, "env"));
        Ok(e)
    }

    /// Generated `$CODEX_HOME/config.toml`. Credentials are stored in `auth.json` (file
    /// store) so they can be leased and written back; update checks are disabled because
    /// CLI versions are pinned in the image.
    pub fn config_toml(ctx: &DriverContext) -> String {
        let mut s = String::from(
            "# generated by acp-runner — do not edit inside the sandbox\n\
             cli_auth_credentials_store = \"file\"\n\
             check_for_update_on_startup = false\n",
        );
        if let Some(extra) = cfg_str(&ctx.config, "extraConfigToml") {
            s.push_str("\n# runner class extraConfigToml\n");
            s.push_str(&extra);
            s.push('\n');
        }
        s
    }
}

#[async_trait]
impl AgentDriver for CodexDriver {
    fn name(&self) -> &'static str {
        "codex"
    }

    fn protocol(&self) -> &'static str {
        "acp/1"
    }

    async fn probe(&self, ctx: &DriverContext) -> Result<ProbeReport, DriverError> {
        let envv = env::compose(ctx, &Self::driver_env(ctx)?)?;
        let adapter = Self::adapter(ctx);
        let mut notes = vec![];
        let adapter_version =
            match crate::run_capture(&adapter, &["--version"], &envv, &ctx.workspace, Duration::from_secs(20)).await {
                Ok((out, _, Some(0))) => out.split_whitespace().last().map(str::to_string),
                Ok((_, err, code)) => {
                    notes.push(format!("codex-acp --version exited {code:?}: {}", err.trim()));
                    None
                }
                Err(DriverError::NotInstalled(p)) => return Err(DriverError::NotInstalled(p)),
                Err(e) => {
                    notes.push(e.to_string());
                    None
                }
            };
        let cli = Self::codex_cli(ctx);
        let cli_version = match crate::run_capture(&cli, &["--version"], &envv, &ctx.workspace, Duration::from_secs(20))
            .await
        {
            Ok((out, _, Some(0))) => out.lines().last().and_then(|l| l.split_whitespace().last()).map(str::to_string),
            Ok((_, err, _)) => {
                notes.push(format!("codex --version failed: {}", err.trim()));
                None
            }
            Err(e) => {
                notes.push(e.to_string());
                None
            }
        };
        let auth_file = Self::codex_home(ctx).join("auth.json");
        let auth = if !auth_file.exists() {
            AuthState::EnrollmentRequired { detail: format!("{} not present", auth_file.display()) }
        } else {
            match crate::run_capture(&cli, &["login", "status"], &envv, &ctx.workspace, Duration::from_secs(30)).await {
                Ok((out, err, code)) => classify_login_status(&format!("{out}\n{err}"), code),
                Err(e) => AuthState::Unknown { detail: e.to_string() },
            }
        };
        Ok(ProbeReport {
            driver: "codex".into(),
            executable: resolve_in_path(&adapter, ctx.path_env.as_deref()).map(|p| p.to_string_lossy().to_string()),
            cli_version,
            adapter_version,
            auth,
            notes,
        })
    }

    async fn prepare(&self, ctx: &DriverContext) -> Result<(), DriverError> {
        let home = Self::codex_home(ctx);
        if home.starts_with("/tmp") {
            // Codex only warns ("could not create PATH aliases") but helper binaries are
            // unavailable; the pod layout uses /home/agent.
            tracing::warn!(codex_home = %home.display(), "CODEX_HOME under /tmp: codex will not create helper PATH aliases");
        }
        tokio::fs::create_dir_all(home.join("log")).await.map_err(|e| DriverError::Io(e.to_string()))?;
        set_mode(&home, 0o700)?;
        tokio::fs::write(home.join("config.toml"), Self::config_toml(ctx))
            .await
            .map_err(|e| DriverError::Io(e.to_string()))?;
        Ok(())
    }

    async fn spawn(&self, ctx: &DriverContext) -> Result<Box<dyn AgentProcess>, DriverError> {
        let launch = AcpLaunch {
            driver: "codex",
            program: Self::adapter(ctx),
            args: cfg_str_list(&ctx.config, "adapterArgs"),
            env: env::compose(ctx, &Self::driver_env(ctx)?)?,
            cwd: None,
        };
        Ok(Box::new(AcpProcess::spawn(ctx, launch)?))
    }

    fn acp_spawn(&self, ctx: &DriverContext) -> Result<crate::process::SpawnSpec, DriverError> {
        Ok(crate::process::SpawnSpec {
            program: Self::adapter(ctx),
            args: cfg_str_list(&ctx.config, "adapterArgs"),
            env: env::compose(ctx, &Self::driver_env(ctx)?)?,
            cwd: ctx.workspace.clone(),
        })
    }
}

/// Map `codex login status` output to an auth state (strings from codex-rs cli/src/login.rs).
pub fn classify_login_status(output: &str, code: Option<i32>) -> AuthState {
    let o = output.to_ascii_lowercase();
    if o.contains("logged in using an api key") || o.contains("bedrock") {
        return AuthState::PolicyViolation { detail: "Codex is logged in with an API key / Bedrock key".into() };
    }
    if code == Some(0) {
        for (needle, method) in [
            ("logged in using chatgpt", "chatgpt"),
            ("logged in using personal access token", "personal-access-token"),
            ("logged in using access token", "access-token"),
            ("logged in using workload identity", "workload-identity"),
        ] {
            if o.contains(needle) {
                return AuthState::Ready { method: method.into() };
            }
        }
        return AuthState::Unknown { detail: "unrecognized `codex login status` output".into() };
    }
    if o.contains("not logged in") {
        return AuthState::EnrollmentRequired { detail: "codex reports: Not logged in".into() };
    }
    AuthState::Unknown { detail: format!("codex login status exited {code:?}") }
}

pub(crate) fn resolve_in_path(program: &str, path_env: Option<&str>) -> Option<PathBuf> {
    if program.contains('/') {
        let p = PathBuf::from(program);
        return p.exists().then_some(p);
    }
    let path = path_env.map(str::to_string).unwrap_or_else(|| env::DEFAULT_PATH.to_string());
    path.split(':').map(|d| Path::new(d).join(program)).find(|p| p.is_file())
}

fn set_mode(p: &Path, mode: u32) -> Result<(), DriverError> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(p, std::fs::Permissions::from_mode(mode)).map_err(|e| DriverError::Io(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tests::ctx;

    #[test]
    fn login_status_classification() {
        assert_eq!(
            classify_login_status("Logged in using ChatGPT\n", Some(0)),
            AuthState::Ready { method: "chatgpt".into() }
        );
        assert!(matches!(
            classify_login_status("Logged in using an API key - sk-***abc\n", Some(0)),
            AuthState::PolicyViolation { .. }
        ));
        assert!(matches!(classify_login_status("Not logged in\n", Some(1)), AuthState::EnrollmentRequired { .. }));
    }

    #[test]
    fn env_contains_codex_home_and_no_browser_and_mode() {
        let mut c = ctx();
        c.config = serde_json::json!({"model": "gpt-5.5-codex"});
        let e = CodexDriver::driver_env(&c).unwrap();
        let get = |k: &str| e.iter().find(|(ek, _)| ek == k).map(|(_, v)| v.clone());
        assert!(get("CODEX_HOME").unwrap().ends_with(".codex"));
        assert_eq!(get("NO_BROWSER").as_deref(), Some("1"));
        assert_eq!(get("INITIAL_AGENT_MODE").as_deref(), Some(DEFAULT_MODE));
        assert!(get("CODEX_CONFIG").unwrap().contains("gpt-5.5-codex"));
        c.config = serde_json::json!({"mode": "yolo"});
        assert!(CodexDriver::driver_env(&c).is_err());
    }

    #[test]
    fn config_toml_uses_file_store_and_disables_update_checks() {
        let t = CodexDriver::config_toml(&ctx());
        assert!(t.contains("cli_auth_credentials_store = \"file\""));
        assert!(t.contains("check_for_update_on_startup = false"));
    }
}
