//! Kubernetes adapter for acp-runner.
//!
//! * [`crds`]: `ACPRunnerClass` and `ACPRun` custom resources and their conversion to the
//!   provider-neutral domain model.
//! * [`pod`]: hardened attempt pod / per-attempt Secret construction.
//! * [`backends`]: `PodBackend` and `AgentSandboxBackend` implementations of the engine's
//!   `SandboxBackend` trait.
//! * [`secret_store`]: Secret-backed `CredentialStore`.

pub mod backends;
pub mod crds;
pub mod pod;
pub mod secret_store;

use kube::CustomResourceExt;

/// Render both CRDs as a multi-document YAML stream (used by `crdgen`).
pub fn crds_yaml() -> String {
    let mut out = String::from("# Generated by `acp-runner-controller crdgen` — do not edit.\n");
    for crd in [crds::ACPRunnerClass::crd(), crds::ACPRun::crd(), crds::AgentEnvironment::crd()] {
        let mut v = serde_json::to_value(&crd).expect("crd serializes");
        normalize_formats(&mut v);
        out.push_str("---\n");
        out.push_str(&serde_yaml::to_string(&v).expect("crd serializes"));
    }
    out
}

/// schemars emits `format: uint64/uint32` for unsigned integers, which the API server does
/// not recognize. Map them to the OpenAPI formats Kubernetes knows plus `minimum: 0`.
fn normalize_formats(v: &mut serde_json::Value) {
    match v {
        serde_json::Value::Object(m) => {
            let replacement = match m.get("format").and_then(|f| f.as_str()) {
                Some("uint64") | Some("uint") => Some("int64"),
                Some("uint32") | Some("uint16") | Some("uint8") => Some("int32"),
                _ => None,
            };
            if let Some(r) = replacement {
                m.insert("format".into(), serde_json::json!(r));
                m.entry("minimum").or_insert(serde_json::json!(0));
            }
            // schemars renders `Option<Enum>` as `enum: [..variants.., null]`; a structural
            // CRD schema requires `nullable: true` and no bare null in the enum list.
            if let Some(serde_json::Value::Array(vals)) = m.get_mut("enum")
                && vals.iter().any(|v| v.is_null())
            {
                vals.retain(|v| !v.is_null());
                m.insert("nullable".into(), serde_json::json!(true));
            }
            m.values_mut().for_each(normalize_formats);
        }
        serde_json::Value::Array(a) => a.iter_mut().for_each(normalize_formats),
        _ => {}
    }
}
